# Generated by Django 5.2.7 on 2025-10-15 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hearing', models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Not Completed', max_length=20)),
                ('reading', models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Not Completed', max_length=20)),
                ('thursday_chanting_session', models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20)),
                ('friday_chanting_session', models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20)),
                ('weekly_discussion', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20)),
                ('sloka_audio_posted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('chanting_mon', models.PositiveIntegerField(default=0)),
                ('chanting_tue', models.PositiveIntegerField(default=0)),
                ('chanting_wed', models.PositiveIntegerField(default=0)),
                ('chanting_thu', models.PositiveIntegerField(default=0)),
                ('chanting_fri', models.PositiveIntegerField(default=0)),
                ('chanting_sat', models.PositiveIntegerField(default=0)),
                ('chanting_sun', models.PositiveIntegerField(default=0)),
                ('seva_done', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('feedback_for_this_week', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='devotee.week')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
