# Generated by Django 5.2.7 on 2025-10-23 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='chanting_fri',
            new_name='daily_chanting',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='hearing',
            new_name='daily_hearing',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='reading',
            new_name='daily_reading',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='friday_chanting_session',
            new_name='friday_morning_chanting_session_attendance',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='thursday_chanting_session',
            new_name='thursday_morning_chanting_session_attendance',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='weekly_discussion',
            new_name='weekly_discussion_session',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='seva_done',
            new_name='weekly_seva',
        ),
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='sloka_audio_posted',
            new_name='weekly_sloka_audio_posted',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_mon',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_sat',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_sun',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_thu',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_tue',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='chanting_wed',
        ),
        migrations.CreateModel(
            name='MonthlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('one_to_one_meeting_conducted_with_counselor', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('monthly_morning_program', models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20)),
                ('monthly_book_completed', models.CharField(choices=[('Completed', 'Completed'), ('Partially Completed', 'Partially Completed'), ('Not Completed', 'Not Completed')], default='Not Completed', max_length=20)),
                ('book_name', models.CharField(max_length=100)),
                ('book_discussion_attended', models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weeks', models.ManyToManyField(related_name='monthly_activity', to='devotee.week')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
