# Generated by Django 5.2.7 on 2025-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotee', '0002_rename_chanting_fri_dailyactivity_daily_chanting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='sport_session_attendance',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20),
        ),
    ]
