# Generated by Django 5.2.7 on 2025-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotee', '0003_dailyactivity_sport_session_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='sunday_offline_program_attendance',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='sunday_temple_chanting_session_attendance',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=20),
        ),
    ]
