# Generated by Django 4.1 on 2025-11-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotee', '0004_dailyactivity_sunday_offline_program_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='sport_session_attendance',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended'), ('No Session Today', 'No Session Today')], default='Not Attended', max_length=20),
        ),
    ]
