# Generated by Django 4.1 on 2025-11-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotee', '0005_alter_dailyactivity_sport_session_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyactivity',
            name='book_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
