# Generated by Django 4.1 on 2025-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_date_of_birth_user_initiation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
